@extends('admin.layout.master')

@section('title', 'Add Performance Report')

@section('content')
<div class="main-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="section-card">
                    <div class="card-header">
                        <h3 class="mb-0">Add New Performance Report</h3>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('admin.performance-reports.store') }}" method="POST">
                            @csrf
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="report_name">Report Name</label>
                                        <input type="text" class="form-control" id="report_name" name="report_name" required>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="report_type">Report Type</label>
                                        <select class="form-control" id="report_type" name="report_type" required>
                                            <option value="">Select Type</option>
                                            <option value="Financial">Financial</option>
                                            <option value="Operational">Operational</option>
                                            <option value="Vehicle Utilization">Vehicle Utilization</option>
                                            <option value="Employee Performance">Employee Performance</option>
                                        </select>
                                    </div>
                                </div>
                            </div>

                            <div class="row mt-3">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="period_start">Period Start</label>
                                        <input type="date" class="form-control" id="period_start" name="period_start" required>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="period_end">Period End</label>
                                        <input type="date" class="form-control" id="period_end" name="period_end" required>
                                    </div>
                                </div>
                            </div>

                            <div class="row mt-3">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="generated_by">Generated By</label>
                                        <select class="form-control" id="generated_by" name="generated_by" required>
                                            <option value="">Select User</option>
                                            <option value="1">John Smith</option>
                                            <option value="2">Sarah Johnson</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="status">Status</label>
                                        <select class="form-control" id="status" name="status" required>
                                            <option value="Draft">Draft</option>
                                            <option value="Review">Review</option>
                                            <option value="Completed">Completed</option>
                                            <option value="Archived">Archived</option>
                                        </select>
                                    </div>
                                </div>
                            </div>

                            <div class="row mt-3">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="description">Description</label>
                                        <textarea class="form-control" id="description" name="description" rows="3"></textarea>
                                    </div>
                                </div>
                            </div>

                            <div class="row mt-3">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="key_findings">Key Findings</label>
                                        <textarea class="form-control" id="key_findings" name="key_findings" rows="4"></textarea>
                                    </div>
                                </div>
                            </div>

                            <div class="row mt-3">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="recommendations">Recommendations</label>
                                        <textarea class="form-control" id="recommendations" name="recommendations" rows="3"></textarea>
                                    </div>
                                </div>
                            </div>

                            <div class="row mt-4">
                                <div class="col-md-12">
                                    <button type="submit" class="btn btn-custom">
                                        <i class="fas fa-save mr-2"></i> Save Performance Report
                                    </button>
                                    <a href="{{ route('admin.performance-reports.index') }}" class="btn btn-outline-custom">
                                        <i class="fas fa-arrow-left mr-2"></i> Back to List
                                    </a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection